---
name: TEST
on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:
      command:
        type: string
        description: "Run Command"
        required: true

env:
  AWS_REGION: "us-east-1"
  ALCHEMY_TOKEN: ${{ secrets.PRIVATEKEYTOACCOUNT }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: env
        run: |
          echo $ALCHEMY_TOKEN
          echo $AWS_REGION
          echo $AWS_ACCESS_KEY_ID
      - name: Run Command
        run: |
          ${{ inputs.command }}
