---
name: listener / adhoc
on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:

      listener:
        type: boolean
        description: "Listener"
        required: false

      FromBlock:
        type: string
        description: "From Block"
        required: false

      toBlock:
        type: string
        description: "To Block"
        required: false

env:
  AWS_REGION: "us-east-1"
  ALCHEMY_TOKEN: ${{ secrets.PRIVATEKEYTOACCOUNT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  run_adhoc_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt


      if: github.event.inputs.FromBlock != '' && github.event.inputs.toBlock != ''
        run: |
          python3 advance/main.py  --from_block ${{ github.event.inputs.FromBlock }} --to_block ${{ github.event.inputs.toBlock }}

      if : github.event.inputs.listener == true
        run: |
          python3 listener/main.py